### ISSUE TITLE
CoffeeG's Double Jump issue

### ISSUE THREAD

**Issue by sternschnaube** [ScadeBlock/BugReport#2]
Installed the latest mod version on Fabric 1.20.6.

**Log:** Couldn't load tag minecraft:load as it is missing following references: dbjump:sched (from mr_coffdoublejump)

Features aren't working.

**Comment by ScadeBlock** [comment]
I'll check that soon

**Comment by ScadeBlock** [comment]
Thanks for reporting! I fixed that, check it here : [Modrinth](https://modrinth.com/datapack/coffdoublejump/versions) | [CurseForge](https://www.curseforge.com/minecraft/mc-mods/coffeegs-double-jump/files/all?page=1&pageSize=20)

**Comment by venaminecraft** [comment]
Thanks for the fast fix 😊
