### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by BizCub** [ScadeBlock/BugReport#3]
Not a issue, but can you tell me how to make a mod from a datapack. I know that I need to somehow use some code from git modrinth, but I don't know how. Thank you in advance

**Comment by ScadeBlock** [comment]
Sure! When you upload datapack into modrinth, it will create a page in version tab(take a look at the image below) and then click `Package as mod`. That's all!
![image](https://github.com/ScadeBlock/BugReport/assets/89845150/509ba872-c7b1-4ba7-ba1e-2d81eddbe236)

**Comment by BizCub** [comment]
Thanks a lot!
