### ISSUE TITLE
Wall Climbing conflicts with sneak walking for safety.

### ISSUE THREAD

**Issue by Barujin** [ScadeBlock/BugReport#5]
Mod: Wall Climbing
Minecraft version: 1.21

The button to activate this mod is Shift. That is also the button for sneak/duck walking, which we use to stay on the same block and not fall off. This is a bad conflict since this mod also launches the player up. ??? I cannot find a way to change the key. Clearly, more thought needs to be invested into this mod.

**Comment by ScadeBlock** [comment]
Sorry for the incovinience, but I'll need to explain how this mod works. This mod is originally a "datapack" - which helps make this mod compatible with many Minecraft version. But the downside is this mod CAN'T detect custom keybinding (Only keybinding've set in default Minecraft). However, I'll try my best to make this keybinding configurable. Thanks for reporting!

**Comment by ScadeBlock** [comment]
Fixed in 2.0 Update
