### ISSUE TITLE
Awful Lightning - Only occur when it's raining?

### ISSUE THREAD

**Issue by Cixon** [ScadeBlock/BugReport#6]
How can I do this or can you please send me a edited 1.21.1 version?

**Comment by ScadeBlock** [comment]
I'll will take a look and i'll make a custom settings that allow you to do it. Thanks for your attention

**Comment by ScadeBlock** [comment]
Solved : Added a custom settings in the newest version: Take a look at [the newest version](https://modrinth.com/datapack/coffeegs-awful-lightning/versions) 

## Settings
+ Custom settings : Only occurs lightning when raining 
  - Too enable : `/scoreboard players set $awf.settings al.owr 1` (This settings only works with MC `1.15+` )
 - Too disable (By default): `/scoreboard players set $awf.settings al.owr 0`

**Comment by Cixon** [comment]
thank you! will try it out
