### ISSUE TITLE
No way to change keybind

### ISSUE THREAD

**Issue by 1dumbbunny** [ScadeBlock/BugReport#8]
I'm using the 1.19.2 version of the mod

Climbing is bound to left shift which is also my sneak button. I love to use sneak when building but now when I press it regardless of if I'm near a wall or not my character will start jumping around. I know I can change my sneak keybind but I've been playing since 2011 with my sneak being my left shift and it's going to be fighting YEARS of muscle memory for one mod. Could you add a way to change the keybind? thanks.

edit: i changed the keybind of my sneak and it's actually just bound to sneak itself. WHY? please fix that, super annoying.

**Comment by ScadeBlock** [comment]
What version of `CoffeeG's Wall Climbing` are you using, in the latest version `2.2`  has already fixed the issues. Also to climbing,  you need to face the wall and press both `jump` and `sneak` at the same time.

**Comment by ScadeBlock** [comment]
Unfortunately, due to technical reasons - This mod hasn't supported keybinding yet. Thanks for your attention
